version: "3.7"

services:
    app:
        image: cstable
        platform: linux/x86_64
        build:
            context: .
            dockerfile: dockerfile
        working_dir: /app
        ports:
            - 8811:8811
        volumes:
            - ./:/app
        stdin_open: true
        tty: true
        mem_limit: 1G
