fmod SOLVER-GLOBAL is
    pr NAT .
    pr TIME-CONVERTER .

    --- switch to use modelCheckAll to generate all counterexamples
    op isModelCheckAll : -> Bool .
    eq isModelCheckAll = true .

    --- show progress when conduct model checking at the final layer
    op showProgress : -> Bool .
    eq showProgress = true .

    --- initial seed for random
    op initSeed : -> Nat .
    eq initSeed = 37 .

    --- timeout for Timer
    op timeout : -> Nat .
    eq timeout = 10 seconds .
endfm