in full-maude.maude
in ../debug.maude
in ../mq/buffered-socket.maude
in file.maude
in ../solver-utils.maude
in ../solver-grammar.maude
in ../solver-global.maude
in client.maude

mod SOVLER-COMMANDER is
    pr CLIENT .

    op aClient : -> Oid [ctor] .
    op init : -> Configuration .
    eq init = < aClient : Client | none >
                CreateClientTcpSocket(socketManager, aClient, "localhost", 8811) .
endm

erew <> init .